# Generated by Django 5.2.4 on 2025-07-10 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articoli', '0009_articolo_profilo'),
        ('utenti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articoli', models.ManyToManyField(to='articoli.articolo')),
                ('utente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='utenti.utente')),
            ],
        ),
    ]
