# Generated by Django 5.2.4 on 2025-07-13 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utenti', '0003_alter_portafoglio_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acquirente',
            options={'permissions': [('puo_visualizzare_profilo_acquirente', "Può visualizzare il profilo dell'acquirente")]},
        ),
        migrations.AlterModelOptions(
            name='venditore',
            options={'permissions': [('puo_visualizzare_profilo_venditore', 'Può visualizzare il profilo del venditore')]},
        ),
    ]
