# Generated by Django 5.2.4 on 2025-07-13 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utenti', '0006_alter_venditore_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portafoglio',
            old_name='utente',
            new_name='acquirente',
        ),
    ]
