# Generated by Django 5.2.4 on 2025-07-10 16:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venditori', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('categoria', models.CharField(choices=[('GN', 'Generale'), ('EL', 'Elettronica'), ('CB', 'Cibo'), ('CA', 'Cancelleria')], default='GN', max_length=2)),
                ('descrizione', models.TextField()),
                ('num_articoli', models.IntegerField()),
                ('sconto_percentuale', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('visualizzabile', models.BooleanField(default=True)),
                ('venditore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venditori.venditore')),
            ],
        ),
        migrations.CreateModel(
            name='Immagine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immagine', models.ImageField(upload_to='')),
                ('articolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articoli.articolo')),
            ],
        ),
        migrations.AddField(
            model_name='articolo',
            name='profilo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='immagine_profilo', to='articoli.immagine'),
        ),
    ]
