# Generated by Django 5.2.4 on 2025-07-07 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venditori', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('prezzo', models.FloatField()),
                ('descrizione', models.TextField()),
                ('num_articoli', models.IntegerField()),
                ('sconto_percentuale', models.FloatField()),
                ('venditori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venditori.venditore')),
            ],
        ),
        migrations.CreateModel(
            name='Immagine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immagine', models.ImageField(upload_to='articolo/')),
                ('articolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articoli.articolo')),
            ],
        ),
    ]
