# Generated by Django 5.2.4 on 2025-07-10 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articoli', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='profilo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='immagine_profilo', to='articoli.immagine'),
        ),
    ]
