# Generated by Django 5.2.4 on 2025-07-08 16:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articoli', '0001_initial'),
        ('venditori', '0002_alter_venditore_denominazione'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articolo',
            name='venditori',
        ),
        migrations.AddField(
            model_name='articolo',
            name='categoria',
            field=models.CharField(choices=[('GN', 'Generale'), ('EL', 'Elettronica'), ('CB', 'Cibo'), ('CA', 'Cancelleria')], default='GN', max_length=2),
        ),
        migrations.AddField(
            model_name='articolo',
            name='venditore',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='venditori.venditore'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articolo',
            name='visualizzabile',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='articolo',
            name='prezzo',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='articolo',
            name='sconto_percentuale',
            field=models.ImageField(upload_to='', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
