# Generated by Django 5.2.4 on 2025-07-08 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articoli', '0002_remove_articolo_venditori_articolo_categoria_and_more'),
        ('venditori', '0002_alter_venditore_denominazione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='venditore',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='venditori.venditore'),
        ),
    ]
