# Generated by Django 5.2.4 on 2025-07-08 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articoli', '0003_alter_articolo_venditore'),
        ('venditori', '0002_alter_venditore_denominazione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='venditore',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='venditori.venditore'),
        ),
    ]
