# Generated by Django 5.2.4 on 2025-07-08 17:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articoli', '0005_alter_articolo_venditore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='sconto_percentuale',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
