# Generated by Django 5.2.4 on 2025-07-08 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articoli', '0006_alter_articolo_sconto_percentuale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='sconto_percentuale',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='immagine',
            name='immagine',
            field=models.ImageField(upload_to='media/articolo/'),
        ),
    ]
