# Generated by Django 5.2.4 on 2025-07-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articoli', '0007_alter_articolo_sconto_percentuale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immagine',
            name='immagine',
            field=models.ImageField(upload_to=''),
        ),
    ]
