# Generated by Django 5.2.4 on 2025-07-09 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articoli', '0008_alter_immagine_immagine'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='profilo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='immagine_profilo', to='articoli.immagine'),
        ),
    ]
