# Generated by Django 5.2.4 on 2025-07-12 17:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utenti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('categoria', models.CharField(choices=[('GN', 'Generale'), ('EL', 'Elettronica'), ('CB', 'Cibo'), ('CA', 'Cancelleria')], default='GN', max_length=2)),
                ('descrizione', models.TextField()),
                ('num_articoli', models.IntegerField()),
                ('sconto_percentuale', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('visualizzabile', models.BooleanField(default=True)),
                ('venditore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utenti.venditore')),
            ],
            options={
                'permissions': [('puo_modificare_articolo', "Può modificare un'articolo"), ('puo_acquistare_articolo', "Può acquistare un'articolo"), ('puo_aggiungere_articolo', "Può aggiungere un'articolo")],
            },
        ),
        migrations.CreateModel(
            name='Carrello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articoli', models.ManyToManyField(to='shop.articolo')),
                ('utente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='utenti.utente')),
            ],
            options={
                'permissions': [('puo_aggiungere_carrello', 'Può aggiungere nel carrello un articolo'), ('puo_visualizzare_carrello', 'Può visualizzare gli articoli nel carrello')],
            },
        ),
        migrations.CreateModel(
            name='Immagine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immagine', models.ImageField(upload_to='')),
                ('articolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.articolo')),
            ],
        ),
        migrations.AddField(
            model_name='articolo',
            name='profilo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='immagine_profilo', to='shop.immagine'),
        ),
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_acquisto', models.DateField()),
                ('prezzo_acquisto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('articolo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.articolo')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utenti.utente')),
            ],
            options={
                'permissions': [('puo_visualizzare_ordini', 'Può visualizzare i dettagli degli ordini')],
            },
        ),
        migrations.CreateModel(
            name='Valutazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commento', models.TextField(default="L'acquirente non ha voluto lasciare un commento")),
                ('ordine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.ordine')),
            ],
            options={
                'permissions': [('puo_valutare', 'Può dare una valutazione ai propri ordini')],
            },
        ),
    ]
