# Generated by Django 5.2.4 on 2025-07-08 16:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articoli', '0002_remove_articolo_venditori_articolo_categoria_and_more'),
        ('utenti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_acquisto', models.DateField()),
                ('prezzo_acquisto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('articoli', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='articoli.articolo')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utenti.utente')),
            ],
        ),
    ]
