# Generated by Django 5.2.4 on 2025-07-10 16:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articoli', '0001_initial'),
        ('utenti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_acquisto', models.DateField()),
                ('prezzo_acquisto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('articolo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='articoli.articolo')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utenti.utente')),
            ],
        ),
        migrations.CreateModel(
            name='Portafoglio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credito', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('utente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='utenti.utente')),
            ],
        ),
        migrations.CreateModel(
            name='Valutazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('ordine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.ordine')),
            ],
        ),
    ]
