# Generated by Django 5.2.4 on 2025-07-13 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrello',
            old_name='utente',
            new_name='acquirente',
        ),
        migrations.RenameField(
            model_name='ordine',
            old_name='utente',
            new_name='acquirente',
        ),
    ]
