# Generated by Django 5.2.4 on 2025-07-09 11:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articoli', '0009_articolo_profilo'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valutazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('articolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articoli.articolo')),
            ],
        ),
    ]
