# Generated by Django 5.2.4 on 2025-07-09 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_valutazione'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valutazione',
            name='articolo',
        ),
        migrations.AddField(
            model_name='valutazione',
            name='ordine',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.ordine'),
            preserve_default=False,
        ),
    ]
