# Generated by Django 5.2.4 on 2025-07-09 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_valutazione_articolo_valutazione_ordine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordine',
            old_name='articoli',
            new_name='articolo',
        ),
    ]
