# Generated by Django 5.2.4 on 2025-07-13 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_articolo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articolo',
            options={'permissions': [('puo_modificare_articolo', "Può modificare un'articolo"), ('puo_acquistare_articolo', "Può acquistare un'articolo"), ('puo_aggiungere_articolo', "Può aggiungere un'articolo"), ('puo_visualizzare_articoli_venditore', 'Può visualizzare gli articoli di un venditore'), ('puo_eliminare_articolo', "Può eliminare l'articolo di un venditore")]},
        ),
    ]
