# Generated by Django 5.2.4 on 2025-07-13 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_articolo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='num_articoli',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='carrello',
            name='articoli',
            field=models.ManyToManyField(blank=True, to='shop.articolo'),
        ),
    ]
