# Generated by Django 5.2.4 on 2025-07-09 21:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_articoli_ordine_articolo'),
        ('utenti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portafoglio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credito', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('utente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='utenti.utente')),
            ],
        ),
    ]
