# Generated by Django 5.2.4 on 2025-07-13 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_articolo_num_articoli_alter_carrello_articoli'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrello',
            options={'permissions': [('puo_aggiungere_carrello', 'Può aggiungere nel carrello un articolo'), ('puo_visualizzare_carrello', 'Può visualizzare gli articoli nel carrello'), ('puo_eliminare_carrello_articolo', "Può eliminare un'articolo nel carrello")]},
        ),
    ]
